# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octrafic < Formula
  desc "Test APIs naturally with AI - OpenAPI specs, natural language, intelligent responses"
  homepage "https://octrafic.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.1.0/octrafic_Darwin_x86_64.tar.gz"
      sha256 "83b4be5fa69f6353c11552352a2e8bffaa82cc34c9c191659f2b0c9da75de7a6"

      def install
        bin.install "octrafic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.1.0/octrafic_Darwin_arm64.tar.gz"
      sha256 "ffa27ff7f7387be564a8638b9f0fc3899e2105f30614bfa30d5f46be2a5b108e"

      def install
        bin.install "octrafic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.1.0/octrafic_Linux_x86_64.tar.gz"
      sha256 "c1e89ea57ff56ba0ab7429fc235f6568dac4a1b9ebaf41f375089459bd1e18a7"
      def install
        bin.install "octrafic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.1.0/octrafic_Linux_arm64.tar.gz"
      sha256 "fc4c33ad1558d27b29c118199d4da91f615a074b3ac388793ef10e7748a32018"
      def install
        bin.install "octrafic"
      end
    end
  end

  test do
    system "#{bin}/octrafic", "--help"
  end
end
