# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octrafic < Formula
  desc "Test APIs naturally with AI - OpenAPI specs, natural language, intelligent responses"
  homepage "https://octrafic.com"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.4.2/octrafic_Darwin_x86_64.tar.gz"
      sha256 "69b9e922dd290e9df5fa302aa41cee3df7bb1e778a3648469b4ea205d5c2e384"

      define_method(:install) do
        bin.install "octrafic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.4.2/octrafic_Darwin_arm64.tar.gz"
      sha256 "f24f0bc6111710b957258279a72b2be3d6687ee4db8022f068c6faa895e4f175"

      define_method(:install) do
        bin.install "octrafic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.4.2/octrafic_Linux_x86_64.tar.gz"
      sha256 "e9368ceb0bf9fb625af0f647982f4cb81e2a1874cce99b7c3e606892f8318769"
      define_method(:install) do
        bin.install "octrafic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Octrafic/octrafic-cli/releases/download/v0.4.2/octrafic_Linux_arm64.tar.gz"
      sha256 "f6838e78429a7299d4596fc32a9cd57a4b0d609f5e6056f3e8ac0f409abf1cde"
      define_method(:install) do
        bin.install "octrafic"
      end
    end
  end

  test do
    system "#{bin}/octrafic", "--help"
  end
end
